apiVersion: v1
kind: ServiceAccount
metadata:
  name: paradigm-workflow
  namespace: paradigm

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: paradigm-workflow
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - update
  - delete
  - patch
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - update
  - delete
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: paradigm-workflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: paradigm-workflow
subjects:
- kind: ServiceAccount
  name: paradigm-workflow
  namespace: paradigm